FROM pek-lava.wrs.com/lava-master:2018.09.07

# Init fstab, auto mount
COPY scripts/fstab           /etc/fstab

# Setup lava environment in rc.local
COPY scripts/rc.local.script  /etc/rc.local
COPY scripts/rc.local.service /etc/init.d/rc.local
RUN cd /etc/rc5.d/ && \
 chmod +x /etc/rc.local && \
 chmod +x /etc/init.d/rc.local && \
 rm -rf S06rc.local && \
 ln -s ../init.d/rc.local S06rc.local 

# Crontabs/root install
COPY scripts/crontab_root    /var/spool/cron/crontabs/root

# Clone lava-extra and patch code. 
RUN rm -rf /opt/lava-extra && \
 git clone git://git.wrs.com/git/lava-extra /opt/lava-extra

# Clone lava-test-definitions
RUN rm -rf /opt/lava-test-definitions && \
 git clone git://git.wrs.com/git/lava-test-definitions /opt/lava-test-definitions

# Setting apache2.
COPY scripts/lava-extra.conf /etc/apache2/sites-available/
COPY scripts/ports.conf      /etc/apache2/
RUN \
 echo 'lava-server : setting apache2' && \
 a2enmod proxy && \
 a2enmod proxy_http && \
 a2dissite 000-default && \
 a2ensite lava-server.conf && \
 a2ensite lava-extra.conf

#uncomment if you want to use squid
RUN sed -i 's,^.*http_proxy:.*,  http_proxy: http://squid:3128,' /etc/lava-server/env.yaml

# Caution to not use any port between the Linux dynamic port range: 32768-60999
RUN sed -i 's,XNBD_PORT_RANGE_MIN.*,XNBD_PORT_RANGE_MIN=61950,' /usr/lib/python3/dist-packages/lava_common/constants.py
RUN sed -i 's,XNBD_PORT_RANGE_MAX.*,XNBD_PORT_RANGE_MAX=62000,' /usr/lib/python3/dist-packages/lava_common/constants.py

#comment this if you do HTTPS (For reenabling CSRF cookie)
COPY settings.conf /etc/lava-server/

EXPOSE 69/udp 80 3079 5555 5556

CMD ["/sbin/init"]
