FROM lavadocker_lava-master:latest 

COPY scripts/lava-extra.conf /etc/apache2/sites-available/
COPY scripts/ports.conf /etc/apache2/
COPY scripts/fstab      /etc/fstab

# Run start.sh as rc.local
COPY scripts/start.sh   /etc/rc.local
COPY scripts/rc.local   /etc/init.d/rc.local
RUN cd /etc/rc5.d/ && ln -s ../init.d/rc.local S06rc.local 

# Clone lava-extra and patch code. 
RUN git clone git://git.wrs.com/git/lava-extra /opt/lava-extra

# Clone lava-test-definitions
RUN git clone git://git.wrs.com/git/lava-test-definitions

RUN \
 echo 'lava-server : setting apache2' && \
 a2enmod proxy && \
 a2enmod proxy_http && \
 a2dissite 000-default && \
 a2ensite lava-server.conf && \
 a2ensite lava-extra.conf

#uncomment if you want to use squid
RUN sed -i 's,^.*http_proxy:.*,  http_proxy: http://squid:3128,' /etc/lava-server/env.yaml

#comment this if you do HTTPS (For reenabling CSRF cookie)
COPY settings.conf /etc/lava-server/

EXPOSE 69/udp 80 3079 5555 5556

CMD ["/sbin/init"]
