FROM ubuntu:20.04 

RUN \
 apt-get clean && \
 apt-get update

# Install debian packages used by the container
# Configure apache to run the lava server
# Log the hostname used during install for the slave name
# e2fsprogs is for libguestfs
RUN \
 echo 'lava-server   lava-server/instance-name string lava-docker-instance' | debconf-set-selections && \
 echo 'locales locales/locales_to_be_generated multiselect C.UTF-8 UTF-8, en_US.UTF-8 UTF-8 ' | debconf-set-selections && \
 echo 'locales locales/default_environment_locale select en_US.UTF-8' | debconf-set-selections && \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 locales \
 postgresql \
 screen \
 sudo \
 wget \
 e2fsprogs \
 gnupg \
 iputils-ping \
 sshpass \
 python3-pycurl \
 python3-paramiko \
 python3-psutil \
 python3-yaml \
 vim || \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 locales \
 postgresql \
 screen \
 sudo \
 wget \
 e2fsprogs \
 gnupg \
 iputils-ping \
 sshpass \
 python3-pycurl \
 python3-paramiko \
 python3-psutil \
 python3-yaml \
 vim 

RUN \
 wget https://apt.lavasoftware.org/lavasoftware.key.asc && \
 apt-key add lavasoftware.key.asc && \
 echo 'deb https://apt.lavasoftware.org/daily buster main' > /etc/apt/sources.list.d/lava.list && \
 apt-get clean && apt-get update

RUN \
 service postgresql start && \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 ser2net \
 u-boot-tools \
 qemu-kvm \
 qemu-system \
 qemu-system-arm \
 qemu-system-i386 \
 python-setproctitle \
 lava-server \
 lava-common \
 lava-coordinator \
 lava-dispatcher \
 lava-server-doc \
 lavacli || \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 ser2net \
 u-boot-tools \
 qemu-kvm \
 qemu-system \
 qemu-system-arm \
 qemu-system-i386 \
 python-setproctitle \
 lava-common \
 lava-coordinator \
 lava-dispatcher \
 lava-server-doc \
 lavacli

#Install docs html
RUN \
 DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
 python3-sphinx \
 python3-sphinx-bootstrap-theme \
 git \
 make || \
 DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
 python3-sphinx \
 python3-sphinx-bootstrap-theme \
 git \
 make

RUN mkdir -p /app/lava_common /app/doc
COPY ./lava_common/version.py /app/lava_common/version.py
COPY ./lava_common/VERSION /app/lava_common/VERSION
COPY ./doc/v2 /app/doc/v2
RUN sed -i 's@https@http@g' /app/doc/v2/conf.py && \
 make -C /app/doc/v2 html && \
 cp -R  /app/doc/v2/_build/html/* /usr/share/lava-server/static/docs/v2/ && \
 rm -rf /app && \
 find /usr/lib/python3/dist-packages/ -name '__pycache__' -type d -exec rm -r "{}" +

RUN \
 echo 'lava-server : setting apache2' && \
 a2enmod proxy && \
 a2enmod proxy_http && \
 a2dissite 000-default && \
 a2ensite lava-server.conf

#uncomment if you want to use squid
RUN sed -i 's,^.*http_proxy:.*,  http_proxy: http://squid:3128,' /etc/lava-server/env.yaml

#comment this if you do HTTPS (For reenabling CSRF cookie)
COPY settings.conf /etc/lava-server/

EXPOSE 69/udp 80 3079 5500 5555 5556

CMD ["/sbin/init"]
