FROM ubuntu:20.04 

RUN \
 apt-get clean && \
 apt-get update

# Install debian packages used by the container
# Configure apache to run the lava server
# Log the hostname used during install for the slave name
# e2fsprogs is for libguestfs
RUN \
 echo 'lava-server   lava-server/instance-name string lava-slave-instance' | debconf-set-selections && \
 echo 'locales locales/locales_to_be_generated multiselect C.UTF-8 UTF-8, en_US.UTF-8 UTF-8 ' | debconf-set-selections && \
 echo 'locales locales/default_environment_locale select en_US.UTF-8' | debconf-set-selections && \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 locales \
 wget \
 git \
 vim \
 sudo \
 python-setproctitle \
 tftpd-hpa \
 u-boot-tools \
 iputils-ping \
 device-tree-compiler \
 qemu-system \
 qemu-system-arm \
 qemu-system-i386 \
 qemu-kvm \
 sshpass \
 gnupg \
 cron \
 python3-paramiko \
 python3-psutil \
 e2fsprogs || \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 locales \
 wget \
 git \
 vim \
 sudo \
 python-setproctitle \
 tftpd-hpa \
 u-boot-tools \
 iputils-ping \
 device-tree-compiler \
 qemu-system \
 qemu-system-arm \
 qemu-system-i386 \
 qemu-kvm \
 sshpass \
 gnupg \
 cron \
 python3-paramiko \
 python3-psutil \
 e2fsprogs

RUN \
 wget https://apt.lavasoftware.org/lavasoftware.key.asc && \
 apt-key add lavasoftware.key.asc && \
 echo 'deb https://apt.lavasoftware.org/daily buster main' > /etc/apt/sources.list.d/lava.list && \
 apt-get clean && apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
 lava-dispatcher \
 apache2 || \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
 lava-dispatcher \
 apache2

COPY configs/lava-slave /etc/lava-dispatcher/lava-slave
COPY configs/tftpd-hpa /etc/default/tftpd-hpa

# Caution to not use any port between the Linux dynamic port range: 32768-60999
RUN sed -i 's,XNBD_PORT_RANGE_MIN.*,XNBD_PORT_RANGE_MIN=61950,' /usr/lib/python3/dist-packages/lava_common/constants.py
RUN sed -i 's,XNBD_PORT_RANGE_MAX.*,XNBD_PORT_RANGE_MAX=62000,' /usr/lib/python3/dist-packages/lava_common/constants.py

EXPOSE 69/udp 80

CMD ["/sbin/init"]
