FROM lavadocker_lava-slave:latest 

COPY scripts/fstab /etc/fstab

# Run start.sh as rc.local
COPY scripts/start.sh /etc/rc.local
COPY scripts/rc.local /etc/init.d/rc.local
RUN cd /etc/rc5.d/ && \
 rm -rf S06rc.local && \
 ln -s ../init.d/rc.local S06rc.local 

# Clone lava-extra and patch code. 
RUN rm -rf /opt/lava-extra && \
 git clone git://git.wrs.com/git/lava-extra /opt/lava-extra

# Clone lava-test-definitions
RUN rm -rf /opt/lava-test-definitions && \
 git clone git://git.wrs.com/git/lava-test-definitions /opt/lava-test-definitions

COPY configs/lava-slave /etc/lava-dispatcher/lava-slave
COPY configs/tftpd-hpa /etc/default/tftpd-hpa

# Caution to not use any port between the Linux dynamic port range: 32768-60999
RUN sed -i 's,XNBD_PORT_RANGE_MIN.*,XNBD_PORT_RANGE_MIN=61950,' /usr/lib/python3/dist-packages/lava_common/constants.py
RUN sed -i 's,XNBD_PORT_RANGE_MAX.*,XNBD_PORT_RANGE_MAX=62000,' /usr/lib/python3/dist-packages/lava_common/constants.py

# Set lava-master while dispatcher lava-slave
RUN sed -i -e "s/{LAVA_MASTER}/lava-master/g" /etc/lava-dispatcher/lava-slave

EXPOSE 69/udp 80

CMD ["/sbin/init"]
